### ISSUE TITLE
Request support for Sankakucomplex

### ISSUE THREAD

**Issue by FirstDagger** [Sixem/imageboard-dl#1]
Would it be possible for you to add support for chan.sankakucomplex.com?

**Comment by sixem** [comment]
If it isn't too much work, sure. I'll look into it when i have some time.

**Comment by sixem** [comment]
I added support for sankaku where it simply iterates through the pages and downloads the posts which i'm guessing is what you meant?

However, the server has a request limit so i also added a `-s` parameter that will sleep for X amount of seconds in between requests. Setting this parameter to 5 seemed to work for me.
