### ISSUE TITLE
Comparison between this and gallery-dl and Hydrus

### ISSUE THREAD

**Issue by DonaldTsang** [Sixem/imageboard-dl#2]
Here are two applications you should take a look at:
- https://github.com/mikf/gallery-dl
- https://github.com/hydrusnetwork/hydrus (https://discord.gg/vy8CUB4)

What does imageboard-dl provide, that is unique from these two applications?

**Comment by sixem** [comment]
I don't think there's anything super unique about this program. This was simply a fun little project i made a couple of years back when i was first messing around with Python, and i'm sure there are better projects out there with more features etc.

The program is here for people to use if they want to, if not that's totally fine. And, after all, there can be more than two applications with the same use case, you know.

**Comment by DonaldTsang** [comment]
@sixem thanks then anyway, would like to talk more about imageboard coverage though. The mored coverage it has (for both gallery-dl and this repo), the better it will be.
